name: test_drive
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  supabase_flutter: ^2.0.0

  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.0

  roslibdart: ^0.0.1-dev+4

  dotenv: ^4.2.0

  fluttertoast: ^8.2.6

  image: ^4.1.7

  flutter_rviz: ^0.0.2

  lottie: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/media/qr_payment.jpg
    - assets/media/navigation.json